# Generated by Django 3.2.6 on 2021-12-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_training_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=10)),
                ('age', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_image', models.ImageField(blank=True, upload_to='media/images')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web_training_auth.webtraininguser')),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
